title: SignIn.Org
description: Creating the Internet Identity Layer
minima:
  social_links:
    twitter: signindotorg
    github: signindotorg
    #facebook: SignIn.Org
    instagram: signindotorg
    linkedin: signindotorg
    #telegram: signindotorg

theme: minima

