title: Creating the Internet Identity Layer
email: info@SignIn.Org
description: SignIn.Org is a consortium of industry leaders working to solve personal online identity.
author: "contact us at:"

twitter_username: signindotorg
github_username:  signindotorg
linkedin_username: DickHardt

theme: minima
